### ISSUE TITLE
Some questions about the paper.

### ISSUE THREAD

**Issue by abcxubu** [yyliu01/TraCoCo#4]
Thanks so much for sharing the wonderful work. I learned much from it, but I do not understand some descriptions. 
1. In the Abstract, you said "These perturbations usually keep the spatial input context between views fairly consistent, which may cause the model to learn segmentation patterns from the spatial input contexts instead of the foreground objects.". What is the " spatial input context" mean? What is the difference between the proposed method and the other algorithms to deal with the "spatial input context"? Is it that the proposed method predicts the same place twice, and then calculates the consistency?
2. In Eq. (7), what does a and b looks like? Maybe [0.6, 0.4], [0.7, 0.3]? What does the I(a>gamma) look like? What does the I(a<beta) look like? Why (how) this eq. works?
Hope to hear from you as soon as possible. Thanks in advance.

**Comment by yyliu01** [comment]
Hi @abcxubu ,

I'm sorry for the late response, as I'm currently in a very busy period.

For your first question,

the "spatial input context" in here denotes the 3D context of the input data, as most of the existing algorithms tending to memorise the patterns correlations from the input. In this case, the model can recognise the pattern of the foreground/background voxels from one view but failed if they appear in different contexts.
![image](https://github.com/yyliu01/TraCoCo/assets/102338056/fc1bf1e8-6c59-46a4-9c8c-e57c0173af99)

For example, from the above image, the model might correctly predict the results from the red area in green bounding box, but make different prediction from the red area in blue box. 

Our TraCoCO enforces the overlap regions' consistency via KL divergence, yes, it is what you describes.

For your second question,

please take a look in this [line](https://github.com/yyliu01/TraCoCo/blob/e0b1a457fdc606d9f83832b774a60d1b4ea791e7/Code/VnetLA/Utils/losses.py#L25).

Cheers,
Yuyuan
