### ISSUE TITLE
code for ACDC

### ISSUE THREAD

**Issue by PKQZPC** [yyliu01/TraCoCo#5]
Hello,
﻿
Firstly, I would like to express my gratitude for the outstanding work you have done on this open-source project. It has been incredibly helpful and insightful.
﻿
I am currently working on a project related to the Automated Cardiac Diagnosis Challenge (ACDC), and I was hoping to utilize the relevant code from your repository. However, I could not locate the specific code or module that corresponds to the ACDC challenge. Could you please guide me on where I might find this information?
﻿
Thank you very much for your time and assistance.

**Comment by yyliu01** [comment]
Hey @PKQZPC 

Thanks so much for letting me know. It has been uploaded.

Cheers,
Yuyuan
