### ISSUE TITLE
Request for Baseline Training Code

### ISSUE THREAD

**Issue by BubbleDirk** [yyliu01/TraCoCo#6]
I hope this message finds you well. I have been working on a project that builds upon your methodology and have successfully utilized the open-sourced code you provided. However, I encountered some challenges when attempting to replicate the baseline results reported in your paper. Specifically, the baseline performance on LA dataset I obtained (i.e., only use 10% labeled data for training) is significantly lower than the results you have described.

To ensure that my implementation aligns accurately with your experiments, I was wondering if you could share the original baseline training code. Having access to this would greatly aid in reproducing the baseline results and furthering my research based on your work.

Thank you very much for your time and assistance.

**Comment by yyliu01** [comment]
Hi @BubbleDirk 

Thanks for your interest.

For baseline training code (i.e., with labelled data only), please utilise the code from [UA-MT](https://github.com/yulequan/UA-MT/tree/master/code). To reproduce our results, I believe our training logs and checkpoints for all the benchmarks are released in [this page](https://github.com/yyliu01/TraCoCo/blob/main/docs/results.md). 

Cheers,
Yuyuan
